import { ExamplePrompt } from "./types";

export const CATEGORIES = [
  {
    id: "coding",
    name: "Coding & Dev",
    description: "Software engineering, debugging, and system design specs.",
    iconName: "Code2",
    color: "from-blue-500 to-indigo-600 bg-blue-50/10 text-blue-400 border-blue-500/20",
    hoverColor: "hover:bg-blue-500/10",
  },
  {
    id: "image generation",
    name: "Image Generation",
    description: "Detailed style, camera, lighting, and negative prompts.",
    iconName: "ImageIcon",
    color: "from-purple-500 to-pink-600 bg-purple-50/10 text-purple-400 border-purple-500/20",
    hoverColor: "hover:bg-purple-500/10",
  },
  {
    id: "writing",
    name: "Writing & Content",
    description: "Copywriting, blog posts, formal emails, and creative writing.",
    iconName: "FileText",
    color: "from-emerald-500 to-teal-600 bg-emerald-50/10 text-emerald-400 border-emerald-500/20",
    hoverColor: "hover:bg-emerald-500/10",
  },
  {
    id: "video",
    name: "Cinematic Video",
    description: "Camera movements, lighting controls, and visual pacing.",
    iconName: "Video",
    color: "from-red-500 to-orange-600 bg-red-50/10 text-red-400 border-red-500/20",
    hoverColor: "hover:bg-red-500/10",
  },
  {
    id: "business",
    name: "Business Strategy",
    description: "Marketing copy, project briefs, emails, and business analysis.",
    iconName: "Briefcase",
    color: "from-cyan-500 to-blue-600 bg-cyan-50/10 text-cyan-400 border-cyan-500/20",
    hoverColor: "hover:bg-cyan-500/10",
  },
  {
    id: "research",
    name: "Academic Research",
    description: "Summarization, critical analysis, and structured learning.",
    iconName: "BookOpen",
    color: "from-amber-500 to-orange-600 bg-amber-50/10 text-amber-400 border-amber-500/20",
    hoverColor: "hover:bg-amber-500/10",
  },
];

export const TARGET_MODELS = [
  { id: "gemini", name: "Gemini 2.5/3.5", categories: ["all"] },
  { id: "gpt-4o", name: "GPT-4o / ChatGPT", categories: ["all"] },
  { id: "claude-3-5", name: "Claude 3.5 Sonnet", categories: ["coding", "writing", "business", "research"] },
  { id: "midjourney", name: "Midjourney v6", categories: ["image generation"] },
  { id: "stable-diffusion", name: "Stable Diffusion 3", categories: ["image generation"] },
  { id: "sora", name: "Sora / Luma Dream Machine", categories: ["video"] },
  { id: "runway", name: "Runway Gen-3", categories: ["video"] },
  { id: "dall-e-3", name: "DALL-E 3", categories: ["image generation"] },
];

export const OUTPUT_FORMATS = [
  { id: "detailed", name: "Detailed / Comprehensive", description: "Expanded details, rigorous constraints, full context." },
  { id: "concise", name: "Concise / Focused", description: "To the point, clear directions, minimal fluff." },
  { id: "step-by-step", name: "Step-by-Step", description: "Structured sequence, logical flow, analytical depth." },
  { id: "academic", name: "Academic / Professional", description: "Formal, clinical terminology, source-ready style." },
];

export const EXAMPLE_PROMPTS: ExamplePrompt[] = [
  {
    title: "React Navigation Component",
    description: "Create a modern header with mobile drawer menu support",
    rawPrompt: "make a responsive nav bar in react with tailwind and mobile menu toggle link highlights",
    category: "coding",
    targetModel: "gemini",
    format: "detailed",
  },
  {
    title: "Cyberpunk Streetscape",
    description: "Generate a neon-drenched futuristic city scene",
    rawPrompt: "neon cyberpunk city narrow street rainy night flying cars neon signs cinematic highly detailed",
    category: "image generation",
    targetModel: "midjourney",
    format: "detailed",
  },
  {
    title: "SaaS Launch Email Sequence",
    description: "Write a high-converting announcement email series",
    rawPrompt: "write an announcement email sequence for a new prompt engineering platform called refyn",
    category: "writing",
    targetModel: "gpt-4o",
    format: "academic",
  },
  {
    title: "Cinematic Drone Shot",
    description: "Video prompt of a mist-covered forest at sunrise",
    rawPrompt: "drone shot flying over a dense foggy pine tree valley during bright early sunrise orange light",
    category: "video",
    targetModel: "runway",
    format: "step-by-step",
  },
  {
    title: "Competitor Swot Analysis",
    description: "Strategic assessment template for business pitches",
    rawPrompt: "swot analysis for starting an online organic coffee delivery subscription service",
    category: "business",
    targetModel: "claude-3-5",
    format: "step-by-step",
  },
  {
    title: "Explain Quantum Computing",
    description: "Simplify complex theory with easy-to-grasp analogies",
    rawPrompt: "explain quantum entanglement to someone who is 12 years old using sports analogies",
    category: "research",
    targetModel: "gemini",
    format: "detailed",
  },
  {
    title: "Rust CLI File Searcher",
    description: "A secure, multi-threaded text matching utility",
    rawPrompt: "rust program cli search files recursively grep style fast regex matched results multi threading",
    category: "coding",
    targetModel: "claude-3-5",
    format: "detailed",
  },
  {
    title: "Abstract Glassmorphic Sphere",
    description: "Glass fluid sculpture of holographic material properties",
    rawPrompt: "abstract fluid glass sphere prism light refract rainbow holographic pastel render octane render",
    category: "image generation",
    targetModel: "stable-diffusion",
    format: "detailed",
  },
  {
    title: "B2B LinkedIn Hook Generator",
    description: "Attention-grabbing professional micro-blogs",
    rawPrompt: "generate high click linkedin hook formulas for b2b saas founders sharing lessons learned",
    category: "writing",
    targetModel: "gpt-4o",
    format: "concise",
  },
  {
    title: "Lapse Over Fast-paced Station",
    description: "Visual energy and human transit patterns",
    rawPrompt: "time lapse camera stationary central train station people blurred moving lightning shadows rush hour",
    category: "video",
    targetModel: "sora",
    format: "step-by-step",
  },
  {
    title: "Pitch Deck Narrative Arcs",
    description: "Dynamic script for attracting early seed capital",
    rawPrompt: "founder presentation slide flow outline for pre seed series standard 10 slide structural points",
    category: "business",
    targetModel: "claude-3-5",
    format: "detailed",
  },
  {
    title: "Machine Learning Breakdown",
    description: "Visual roadmap of loss optimization mechanics",
    rawPrompt: "explain stochastic gradient descent mathematically but intuitively with simple graphics visual guide",
    category: "research",
    targetModel: "gemini",
    format: "step-by-step",
  },
];
